builds:
-
  env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  - windows
archive:
  replacements:
    darwin: MacOS
    linux: Linux
    windows: Windows
    386: i386
  format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
